# Generated by Django 2.1.7 on 2019-04-15 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190329_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=100)),
                ('acontent', models.TextField()),
                ('apublished', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'User added Tutorial',
            },
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 19, 35, 17, 933934), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='image',
            field=models.ImageField(default=0, upload_to='media/img'),
        ),
    ]
