# Generated by Django 2.1.7 on 2019-04-15 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190415_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtutorial',
            old_name='acontent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='addtutorial',
            old_name='apublished',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='addtutorial',
            name='atitle',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 20, 53, 53, 145066), verbose_name='date published'),
        ),
    ]
