# Generated by Django 2.1.7 on 2019-04-15 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190415_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtutorial',
            name='published',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 21, 50, 22, 888457), verbose_name='date published'),
        ),
    ]
